### PR TITLE
Actions

### PR DESCRIPTION
**Pull request by Schrank**
Thanks @lfolco! I have no clue wether this works, but it looks good to me. I moved it into its own config value, if it doesn't work, someone can just turn it off :D

Feel free to comment, I'm happy to merge it if you (all - not @lfolco alone ;) ) are silent :-)

### CODE REVIEW

**Comment by lfolco** [comment]
I haven't finished the actions yet, so not sure it's a good idea to enable it by default (I've been a bit lax on finishing it...)

**Comment by Schrank** [comment]
✅

**Comment by lfolco** [comment]
I'll give it a spin over the next few days, it's been a while since I looked at this, but I recall there being some major reason why I never merged it into master. Were you able to test it thoroughly?

**Comment by Schrank** [comment]
No, but after that warning I will :D

**Comment by lfolco** [comment]
Closing this to open a new one; I fixed the issue with actions and added tests.

**Pull request closed without merging**
